// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  // Datasource URL is required for migrate dev
  datasource: {
    url: process.env.DATABASE_URL!, // ← MUST be here for migrations
    provider: "postgresql",
  },

  migrations: {
    path: "prisma/migrations",
    provider: "postgresql",
  },
});

